import type { Metadata } from "next";
import theme from '@/theme';
import { ThemeProvider } from '@mui/material/styles';
import { CssBaseline } from "@mui/material";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <ThemeProvider theme={theme}>
      <CssBaseline />
            
        {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
